SELECT * FROM  [dbo].[TB_ACT_OLIST_CUSTOMERS]

CREATE VIEW VW_PEDIDOS_POR_CLIENTE_E_SUA_CIDADE
AS

SELECT O.*,C.CUSTOMER_CITY,C.CUSTOMER_STATE
FROM [dbo].[TB_ACT_OLIST_ORDERS] AS O
INNER JOIN [dbo].[TB_ACT_OLIST_CUSTOMERS] AS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID


ALTER VIEW VW_PEDIDOS_POR_CLIENTE_E_SUA_CIDADE
AS

SELECT O.*
FROM [dbo].[TB_ACT_OLIST_ORDERS] AS O
INNER JOIN [dbo].[TB_ACT_OLIST_CUSTOMERS] AS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE ORDER_STATUS = 'delivered'

SELECT * FROM VW_PEDIDOS_POR_CLIENTE_E_SUA_CIDADE
